version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
     - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8123:8123"
    volumes:
      - ./backend:/app
      - /mlcv1:/mlcv1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']  # Use only GPU 0
              capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=0  # Only use GPU 0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
